# appveyor.yml reference : http://www.appveyor.com/docs/appveyor-yml
version: "2.0.0.{build}"

# Source Config
platform: x64
branches:
  only:
    - master
pull_requests:
  do_not_increment_build_number: true
clone_folder: c:\gopath\src\github.com\pecigonzalo\docker-machine-vmwareworkstation
clone_depth: 5

environment:
  MSYSTEM: MINGW64
  Msys: winsymlink:nativestrict
  GOPATH: c:\gopath
  Path: c:\go\bin;%GOPATH%\bin;C:\msys64\usr\local\bin;C:\msys64\mingw64\bin;C:\msys64\usr\bin;%PATH%

init:
  - ps: git config --global core.autocrlf input
  - pacman -Sy
  - pacman -S --noconfirm --needed make wget curl
  - mkdir -p %GOPATH%\bin
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh

# Build
install:
  - go version
  - go env
  - ps: echo $env:Path
  - make clean
  - make deps

build_script:
  - git rev-parse HEAD
  - make vet test
  - make build

test: off

# Deploy
artifacts:
  - path: /bin/docker-machine-driver-vmwareworkstation.exe

deploy:
  provider: GitHub
  description: ' '
  auth_token:
    secure: QqxdbpN5rJhuQw42Iq4W6tdP1Lu4aw6y88QnHYC3tSQ9rzNuEI/q+qH4HGJ5WDpj
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: true        # deploy on tag push only
